[package]
name = "velora-panel-communications"
version.workspace = true
edition.workspace = true
license = "MIT"
repository = "https://github.com/VeloraMCDev/velora-launcher"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lettre = { version = "0.11", default-features = false, features = ["builder", "smtp-transport", "tokio1-rustls-tls"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream", "http2", "gzip"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "net"] }
axum = "0.8"
