// The in-game command guide, shared by the launcher, the web player panel and both command palettes.
// Keep this in step with the Paper/Fabric/Forge command handlers (see docs/commands.md).

export type Cmd = { usage: string; does: string; perm: string; aliases?: string[] };
export type CommandGroup = { title: string; blurb: string; cmds: Cmd[] };

export const COMMAND_GROUPS: CommandGroup[] = [
  { title: 'Getting around', blurb: 'Teleports, homes and warps.', cmds: [
    { usage: '/spawn', does: 'Teleport to the server spawn.', perm: 'scopenet.command.spawn', aliases: ['hub', 'lobby'] },
    { usage: '/home [name]', does: 'Teleport to a home, or open the homes menu.', perm: 'scopenet.command.home', aliases: ['homes'] },
    { usage: '/sethome [name]', does: 'Save your current spot as a home.', perm: 'scopenet.command.sethome' },
    { usage: '/delhome <name>', does: 'Delete one of your homes.', perm: 'scopenet.command.delhome', aliases: ['rmhome'] },
    { usage: '/back', does: 'Return to where you were, or where you died.', perm: 'scopenet.command.back', aliases: ['return'] },
    { usage: '/warp [name]', does: 'Go to a server warp, or open the warps menu.', perm: 'scopenet.command.warp', aliases: ['warps'] },
    { usage: '/reqwarp <name>', does: 'Request a public warp at your current location.', perm: 'scopenet.command.reqwarp' },
    { usage: '/warprequests', does: 'Staff: list pending warp requests.', perm: 'scopenet.command.warp.manage' },
    { usage: '/warpapprove <name> · /warpdeny <name>', does: 'Staff: approve or deny a warp request.', perm: 'scopenet.command.warp.manage' },
    { usage: '/setwarp <name> · /delwarp <name>', does: 'Staff: create or delete public warps.', perm: 'scopenet.command.warp.manage' },
    { usage: '/rtp', does: 'Jump to a random safe spot in the wild.', perm: 'scopenet.command.rtp', aliases: ['wild', 'randomtp'] },
    { usage: '/tpa <player>', does: 'Ask to teleport to another player.', perm: 'scopenet.command.tpa' },
    { usage: '/tpaccept', does: 'Accept a teleport request.', perm: 'scopenet.command.tpaccept', aliases: ['tpyes'] },
    { usage: '/tpdeny', does: 'Decline a teleport request.', perm: 'scopenet.command.tpdeny', aliases: ['tpno'] },
  ] },
  { title: 'Money & trading', blurb: 'Your balance, the shop, the market and player trades.', cmds: [
    { usage: '/balance', does: 'Check your balance.', perm: 'scopenet.command.balance', aliases: ['bal', 'money'] },
    { usage: '/pay <player> <amount>', does: 'Send money to a player.', perm: 'scopenet.command.pay' },
    { usage: '/baltop', does: 'See the richest players.', perm: 'scopenet.command.baltop', aliases: ['richest'] },
    { usage: '/shop', does: 'Open the server shop.', perm: 'scopenet.command.shop' },
    { usage: '/sell hand', does: 'Sell the item in your hand to the shop.', perm: 'scopenet.command.sell.hand' },
    { usage: '/sell', does: 'Open the selling menu.', perm: 'scopenet.command.sell' },
    { usage: '/market', does: 'Browse and buy from the player market.', perm: 'scopenet.command.market', aliases: ['ah', 'auction'] },
    { usage: '/market sell [price]', does: 'Sell the item in your hand for a fixed price. Without a price, a window lets you pick Buy Now or Auction with buttons.', perm: 'scopenet.command.market.sell' },
    { usage: '/market auction [starting bid] [hours]', does: 'Start an auction for the item in your hand (1–168 hours, 24 by default). Highest bid wins; outbid players are refunded.', perm: 'scopenet.command.market.sell' },
    { usage: '/market bid <#id> [amount]', does: 'Bid on an auction. Leave the amount out to bid the minimum. A late bid adds two minutes.', perm: 'scopenet.command.market.buy' },
    { usage: '/market claim', does: 'Collect auctions you won and items that came back unsold.', perm: 'scopenet.command.market.buy', aliases: ['/market mailbox'] },
    { usage: '/market cancel <#id>', does: 'Take your own listing down (auctions only before the first bid).', perm: 'scopenet.command.market.sell' },
    { usage: '/market point add <name> [market|shop]', does: 'Staff: turn the block you look at into a shop that opens the market or shop when right-clicked. Also shown on the map.', perm: 'scopenet.command.market.point' },
    { usage: '/orders', does: 'View your active market orders.', perm: 'scopenet.command.orders' },
    { usage: '/trade <player>', does: 'Start a secure trade with another player.', perm: 'scopenet.command.trade' },
    { usage: '/transactions', does: 'See your recent money movements.', perm: 'scopenet.command.transactions' },
  ] },
  { title: 'Guilds & land', blurb: 'Team up, claim land and protect it.', cmds: [
    { usage: '/guild', does: 'Open your guild dashboard.', perm: 'scopenet.command.guild', aliases: ['g', 'clan'] },
    { usage: '/guild create <name> <tag>', does: 'Found a new guild.', perm: 'scopenet.command.guild.create' },
    { usage: '/guild leave', does: 'Leave your guild.', perm: 'scopenet.command.guild.leave' },
    { usage: '/guild members', does: 'List your guild members.', perm: 'scopenet.command.guild.members' },
    { usage: '/guild chat <message>', does: 'Talk to your guild only.', perm: 'scopenet.command.guild.chat', aliases: ['/guild c'] },
    { usage: '/guild sethome · /guild home', does: 'Set or visit the guild home.', perm: 'scopenet.command.guild.sethome' },
    { usage: '/guild map', does: 'Show nearby claims on a map.', perm: 'scopenet.command.guild.map' },
    { usage: '/guild invite <player>', does: 'Invite a player to your guild (leaders and officers).', perm: 'scopenet.command.guild.invite' },
    { usage: '/guild list · /guild info <name>', does: 'Browse the guilds on this server.', perm: 'scopenet.command.guild' },
    { usage: '/guild join <name> [message]', does: 'Ask to join a guild. Its leaders get a notification.', perm: 'scopenet.command.guild' },
    { usage: '/guild requests · approve <player> · reject <player>', does: 'Review join requests (leaders and officers).', perm: 'scopenet.command.guild' },
    { usage: '/guild kick <player>', does: 'Remove a member. Only the leader can remove officers.', perm: 'scopenet.command.guild' },
    { usage: '/guild promote <player> · demote <player>', does: 'Make someone an officer, or a member again (leader).', perm: 'scopenet.command.guild' },
    { usage: '/guild roles · role <player> <role>', does: 'See the roles and give a custom role (leader).', perm: 'scopenet.command.guild' },
    { usage: '/guild transfer <player> confirm', does: 'Hand the guild to someone else; you become an officer.', perm: 'scopenet.command.guild' },
    { usage: '/guild motd <text> · /guild desc <text>', does: 'Set the message of the day or the description.', perm: 'scopenet.command.guild' },
    { usage: '/guild post <title> | <text> · /guild posts', does: 'Post an announcement everyone in the guild is notified about, or read the board.', perm: 'scopenet.command.guild' },
    { usage: '/guild accept [tag] · /guild decline [tag]', does: 'Answer a guild invitation. You can also answer in the launcher.', perm: 'scopenet.command.guild.accept' },
    { usage: '/claim', does: 'Claim the chunk you stand in for your guild.', perm: 'scopenet.command.claim' },
    { usage: '/unclaim', does: 'Give up the chunk you stand in.', perm: 'scopenet.command.unclaim' },
    { usage: '/autoclaim on|off', does: 'Automatically claim new chunks as you walk.', perm: 'scopenet.command.claim' },
  ] },
  { title: 'Guild bank', blurb: 'Shared guild money. Officers and leaders can spend it.', cmds: [
    { usage: '/guild bank', does: 'Show the bank balance and recent activity.', perm: 'scopenet.command.guild.bank' },
    { usage: '/guild bank deposit <amount>', does: 'Put your own money into the bank.', perm: 'scopenet.command.guild.bank.deposit' },
    { usage: '/guild bank withdraw <amount>', does: 'Take money out (officers and leaders).', perm: 'scopenet.command.guild.bank.withdraw' },
    { usage: '/guild sell hand', does: 'Sell your held item and pay the bank.', perm: 'scopenet.command.guild.sell' },
    { usage: '/guild market', does: 'Buy and sell on the market as your guild.', perm: 'scopenet.command.guild.market' },
    { usage: '/guild pay <tag> <amount>', does: 'Pay another guild from your bank.', perm: 'scopenet.command.guild.pay' },
  ] },
  { title: 'Everyday perks', blurb: 'Handy commands you can configure per server. Ask an admin if one is off.', cmds: [
    { usage: '/fly [on|off]', does: 'Fly freely. free.fly works anywhere; guild.fly only inside your own guild’s land (it switches off when you leave).', perm: 'free.fly or guild.fly' },
    { usage: '/heal [player]', does: 'Restore health (the amount and wait are set by the server).', perm: 'scopenet.command.heal' },
    { usage: '/feed [player]', does: 'Restore hunger (the wait is set by the server).', perm: 'scopenet.command.feed' },
    { usage: '/vault [number]', does: 'Open a portable chest. Some vaults need a higher rank.', perm: 'scopenet.command.vault', aliases: ['pv'] },
    { usage: '/echest', does: 'Open your ender chest from anywhere.', perm: 'scopenet.command.echest', aliases: ['ec', 'enderchest'] },
    { usage: '/kit [name]', does: 'List the kits you can claim, or claim one.', perm: 'scopenet.command.kit', aliases: ['kits'] },
    { usage: '/quests [player]', does: 'See your daily and weekly quests, or anyone else’s.', perm: 'scopenet.command.quests', aliases: ['quest', 'dailies'] },
  ] },
  { title: 'Info & admin', blurb: 'Help, the player panel link and staff tools.', cmds: [
    { usage: '/shopkeeper spawn <name> [market|shop] [mob]', does: 'Staff: place a villager (or any mob) that opens the market when right-clicked. It never moves and is marked on the map.', perm: 'scopenet.command.market.point' },
    { usage: '/shopkeeper link <name> · remove <name> · list', does: 'Staff: turn the mob you look at into a shopkeeper, free it again, or list them.', perm: 'scopenet.command.market.point' },
    { usage: '/adminclaim create <name> [description]', does: 'Staff: protect the chunk you stand in as server land with a name and description. Also manage them in the admin panel.', perm: 'scopenet.admin.claims', aliases: ['/aclaim'] },
    { usage: '/customitem give <player> <id>', does: 'Staff: hand out an item designed in the admin panel.', perm: 'scopenet.admin.customitem' },
    { usage: '/playtime', does: 'Check your total and session playtime.', perm: 'scopenet.command.playtime', aliases: ['ontime'] },
    { usage: '/hand', does: 'Share your held item as an inspectable chat link.', perm: 'scopenet.command.hand' },
    { usage: '/nick <name|off>', does: 'Set or remove your chat nickname.', perm: 'scopenet.command.nick' },
    { usage: '/scopenet help', does: 'List the Velora commands you can use.', perm: 'scopenet.command.scopenet.help', aliases: ['sn'] },
    { usage: '/scopenet panel', does: 'Get the link to the player panel: market, casino, friends, guilds and quests in any browser or phone. Sign in with your launcher account.', perm: 'scopenet.command.scopenet.panel', aliases: ['/scopenet web', '/scopenet app'] },
    { usage: '/scopenet status', does: 'Panel connection, features and plugin integrations (admins).', perm: 'scopenet.command.scopenet.status' },
    { usage: '/scopenet reload', does: 'Reload the plugin config (admins).', perm: 'scopenet.command.scopenet.reload' },
  ] },
];

export const COMMAND_TIPS = [
  'Press Ctrl+K in the launcher, the player panel or the admin panel to jump anywhere or find a command instantly.',
  'The player panel works on your phone: market, casino, friends, guilds, quests, leaderboards and the live map. Type /scopenet panel in game for the link, then use “Add to Home Screen”.',
  'Placeholders: use %scopenet_level%, %scopenet_guild%, %scopenet_balance% and more in scoreboards, tab and chat.',
  'Walking into claimed land shows the guild (or the server area and its description) above your hotbar. Your bell in the title bar collects guild, auction and quest news.',
  'Right-click a shop point (a marked block) to open the market or shop. On a server with the Velora client mod it opens the shop window.',
  'Some commands may be switched off or limited by the server. If one says you lack permission, ask an admin.',
  'Everything here also works through your rank: servers using LuckPerms can grant each permission node to any group.',
];
