// The in-game command guide, shared by the launcher, the web player panel and both command palettes.
// Keep this in step with the Paper/Fabric/Forge command handlers (see docs/commands.md).

export type Cmd = { usage: string; does: string; perm: string; aliases?: string[] };
export type CommandGroup = { title: string; blurb: string; cmds: Cmd[] };

export const COMMAND_GROUPS: CommandGroup[] = [
  { title: 'Getting around', blurb: 'Teleports, homes and warps.', cmds: [
    { usage: '/spawn', does: 'Teleport to the server spawn.', perm: 'velora.command.spawn', aliases: ['hub', 'lobby'] },
    { usage: '/home [name]', does: 'Teleport to a home, or open the homes menu.', perm: 'velora.command.home', aliases: ['homes'] },
    { usage: '/sethome [name]', does: 'Save your current spot as a home.', perm: 'velora.command.sethome' },
    { usage: '/delhome <name>', does: 'Delete one of your homes.', perm: 'velora.command.delhome', aliases: ['rmhome'] },
    { usage: '/back', does: 'Return to where you were, or where you died.', perm: 'velora.command.back', aliases: ['return'] },
    { usage: '/warp [name]', does: 'Go to a server warp, or open the warps menu.', perm: 'velora.command.warp', aliases: ['warps'] },
    { usage: '/reqwarp <name>', does: 'Request a public warp at your current location.', perm: 'velora.command.reqwarp' },
    { usage: '/warprequests', does: 'Staff: list pending warp requests.', perm: 'velora.command.warp.manage' },
    { usage: '/warpapprove <name> · /warpdeny <name>', does: 'Staff: approve or deny a warp request.', perm: 'velora.command.warp.manage' },
    { usage: '/setwarp <name> · /delwarp <name>', does: 'Staff: create or delete public warps.', perm: 'velora.command.warp.manage' },
    { usage: '/rtp', does: 'Jump to a random safe spot in the wild.', perm: 'velora.command.rtp', aliases: ['wild', 'randomtp'] },
    { usage: '/tpa <player>', does: 'Ask to teleport to another player.', perm: 'velora.command.tpa' },
    { usage: '/tpaccept', does: 'Accept a teleport request.', perm: 'velora.command.tpaccept', aliases: ['tpyes'] },
    { usage: '/tpdeny', does: 'Decline a teleport request.', perm: 'velora.command.tpdeny', aliases: ['tpno'] },
  ] },
  { title: 'Money & trading', blurb: 'Your balance, the shop, the market and player trades.', cmds: [
    { usage: '/balance', does: 'Check your balance.', perm: 'velora.command.balance', aliases: ['bal', 'money'] },
    { usage: '/pay <player> <amount>', does: 'Send money to a player.', perm: 'velora.command.pay' },
    { usage: '/baltop', does: 'See the richest players.', perm: 'velora.command.baltop', aliases: ['richest'] },
    { usage: '/shop', does: 'Open the server shop.', perm: 'velora.command.shop' },
    { usage: '/sell hand', does: 'Sell the item in your hand to the shop.', perm: 'velora.command.sell.hand' },
    { usage: '/sell', does: 'Open the selling menu.', perm: 'velora.command.sell' },
    { usage: '/market', does: 'Browse and buy from the player market.', perm: 'velora.command.market', aliases: ['ah', 'auction'] },
    { usage: '/market sell [price]', does: 'Sell the item in your hand for a fixed price. Without a price, a window lets you pick Buy Now or Auction with buttons.', perm: 'velora.command.market.sell' },
    { usage: '/market auction [starting bid] [hours]', does: 'Start an auction for the item in your hand (1–168 hours, 24 by default). Highest bid wins; outbid players are refunded.', perm: 'velora.command.market.sell' },
    { usage: '/market bid <#id> [amount]', does: 'Bid on an auction. Leave the amount out to bid the minimum. A late bid adds two minutes.', perm: 'velora.command.market.buy' },
    { usage: '/market claim', does: 'Collect auctions you won and items that came back unsold.', perm: 'velora.command.market.buy', aliases: ['/market mailbox'] },
    { usage: '/market cancel <#id>', does: 'Take your own listing down (auctions only before the first bid).', perm: 'velora.command.market.sell' },
    { usage: '/market point add <name> [market|shop]', does: 'Staff: turn the block you look at into a shop that opens the market or shop when right-clicked. Also shown on the map.', perm: 'velora.command.market.point' },
    { usage: '/darknet', does: 'Browse the Darknet catalog of items you can buy with your balance.', perm: 'velora.command.darknet' },
    { usage: '/darknet buy <product>', does: 'Buy a Darknet product. It is delivered to your vault, and the price shown when you looked is the price you pay.', perm: 'velora.command.darknet' },
    { usage: '/orders', does: 'View your active market orders.', perm: 'velora.command.orders', aliases: ['buyorder', 'bo'] },
    { usage: '/orders request <amount> <total dollars> <item> <deadline minutes>', does: 'Post a buy order and escrow the money. Another player accepts it and hands in the items before your deadline (5 minutes to 30 days); expired orders refund you.', perm: 'velora.command.orders' },
    { usage: '/orders pickup <id> · drop <id> · cancel <id>', does: 'Accept an order, give it back, or cancel your own.', perm: 'velora.command.orders' },
    { usage: '/contracts [list|submit|abandon]', does: 'See your contracts, hand in the items for one, or swap it for another.', perm: 'velora.command.contracts', aliases: ['contract'] },
    { usage: '/pshop create <dollars> [quantity]', does: 'Make a pedestal shop: hold the product and look at a polished blackstone slab, then right-click the linked chest to stock it.', perm: 'velora.command.pshop' },
    { usage: '/pshop price <id> <dollars> · close <id> · reopen <id>', does: 'Change a pedestal shop’s price, or close and reopen it.', perm: 'velora.command.pshop' },
    { usage: '/pshop stock <id>', does: 'Recover stock from one of your shops, even if its blocks are gone.', perm: 'velora.command.pshop' },
    { usage: '/pshop buy', does: 'Buy from the pedestal you looked at after reading the chat quote.', perm: 'velora.command.pshop' },
    { usage: '/pshop promote <id> <1-30 days> [warp] [confirm]', does: 'Pin your shop on the map (and optionally add a warp). Shows the fee first; add confirm to pay.', perm: 'velora.command.pshop' },
    { usage: '/pshop visit <id>', does: 'Teleport to a promoted shop that has a warp.', perm: 'velora.command.pshop' },
    { usage: '/trade <player>', does: 'Start a secure trade with another player.', perm: 'velora.command.trade' },
    { usage: '/transactions', does: 'See your recent money movements.', perm: 'velora.command.transactions' },
  ] },
  { title: 'Factions & land', blurb: 'Team up, claim land and protect it.', cmds: [
    { usage: '/faction', does: 'Open your faction dashboard.', perm: 'velora.command.guild', aliases: ['guild', 'f', 'g', 'clan'] },
    { usage: '/faction create <name> <tag>', does: 'Found a new faction.', perm: 'velora.command.guild.create' },
    { usage: '/faction leave', does: 'Leave your faction.', perm: 'velora.command.guild.leave' },
    { usage: '/faction members', does: 'List your faction members.', perm: 'velora.command.guild.members' },
    { usage: '/faction chat <message>', does: 'Talk to your faction only.', perm: 'velora.command.guild.chat', aliases: ['/guild c'] },
    { usage: '/faction sethome · /faction home', does: 'Set or visit the faction home.', perm: 'velora.command.guild.sethome' },
    { usage: '/faction map', does: 'Show nearby claims on a map.', perm: 'velora.command.guild.map' },
    { usage: '/faction invite <player>', does: 'Invite a player to your faction (leaders and officers).', perm: 'velora.command.guild.invite' },
    { usage: '/faction list · /faction info <name>', does: 'Browse the factions on this server.', perm: 'velora.command.guild' },
    { usage: '/faction join <name> [message]', does: 'Ask to join a faction. Its leaders get a notification.', perm: 'velora.command.guild' },
    { usage: '/faction requests · approve <player> · reject <player>', does: 'Review join requests (leaders and officers).', perm: 'velora.command.guild' },
    { usage: '/faction kick <player>', does: 'Remove a member. Only the leader can remove officers.', perm: 'velora.command.guild' },
    { usage: '/faction promote <player> · demote <player>', does: 'Make someone an officer, or a member again (leader).', perm: 'velora.command.guild' },
    { usage: '/faction roles · role <player> <role>', does: 'See the roles and give a custom role (leader).', perm: 'velora.command.guild' },
    { usage: '/faction transfer <player> confirm', does: 'Hand the faction to someone else; you become an officer.', perm: 'velora.command.guild' },
    { usage: '/faction motd <text> · /faction desc <text>', does: 'Set the message of the day or the description.', perm: 'velora.command.guild' },
    { usage: '/faction post <title> | <text> · /faction posts', does: 'Post an announcement everyone in the faction is notified about, or read the board.', perm: 'velora.command.guild' },
    { usage: '/faction accept [tag] · /faction decline [tag]', does: 'Answer a faction invitation. You can also answer in the launcher.', perm: 'velora.command.guild.accept' },
    { usage: '/faction rename <name> [tag] · /faction disband confirm', does: 'Rename the faction, or disband it (leader).', perm: 'velora.command.guild' },
    { usage: '/faction flags', does: 'Show the protection flags for your faction land.', perm: 'velora.command.guild.flags' },
    { usage: '/faction upgrade [claims|members|outposts|vault] [tier]', does: 'See or buy faction upgrades with the faction bank: more claim capacity, members, outpost flags and vault pages. Repeating a purchase never charges twice.', perm: 'velora.command.guild' },
    { usage: '/faction outpost place', does: 'Hold a purchased Outpost Flag and place it to start a second claim area. Each flag allows twelve chunks within three chunks of it.', perm: 'velora.command.guild' },
    { usage: '/faction vault [page]', does: 'Open shared faction storage (pages 1–9). Leaders, officers and roles with storage access only.', perm: 'velora.command.guild' },
    { usage: '/claim', does: 'Claim the chunk you stand in for your faction.', perm: 'velora.command.claim' },
    { usage: '/unclaim', does: 'Give up the chunk you stand in.', perm: 'velora.command.unclaim' },
    { usage: '/autoclaim on|off', does: 'Automatically claim new chunks as you walk.', perm: 'velora.command.claim' },
  ] },
  { title: 'Faction bank', blurb: 'Shared faction money. Officers and leaders can spend it.', cmds: [
    { usage: '/faction bank', does: 'Show the bank balance and recent activity.', perm: 'velora.command.guild.bank' },
    { usage: '/faction bank deposit <amount>', does: 'Put your own money into the bank.', perm: 'velora.command.guild.bank.deposit' },
    { usage: '/faction bank withdraw <amount>', does: 'Take money out (officers and leaders).', perm: 'velora.command.guild.bank.withdraw' },
    { usage: '/faction sell hand', does: 'Sell your held item and pay the bank.', perm: 'velora.command.guild.sell' },
    { usage: '/faction market', does: 'Buy and sell on the market as your faction.', perm: 'velora.command.guild.market' },
    { usage: '/faction pay <tag> <amount>', does: 'Pay another faction from your bank.', perm: 'velora.command.guild.pay' },
  ] },
  { title: 'Everyday perks', blurb: 'Handy commands you can configure per server. Ask an admin if one is off.', cmds: [
    { usage: '/fly [on|off]', does: 'Fly freely. free.fly works anywhere; guild.fly only inside your own faction’s land (it switches off when you leave).', perm: 'free.fly or guild.fly' },
    { usage: '/heal [player]', does: 'Restore health (the amount and wait are set by the server).', perm: 'velora.command.heal' },
    { usage: '/feed [player]', does: 'Restore hunger (the wait is set by the server).', perm: 'velora.command.feed' },
    { usage: '/vault [number]', does: 'Open one of your cloud vaults. You start with one free page; more are unlocked in the Market > Vaults page, the Darknet or the K menu. Your vaults are also visible in the launcher.', perm: 'velora.command.vault', aliases: ['pv'] },
    { usage: '/echest', does: 'Open your ender chest from anywhere.', perm: 'velora.command.echest', aliases: ['ec', 'enderchest'] },
    { usage: '/kit [name]', does: 'List the kits you can claim, or claim one.', perm: 'velora.command.kit', aliases: ['kits'] },
    { usage: '/quests [player]', does: 'See your daily and weekly quests, or anyone else’s.', perm: 'velora.command.quests', aliases: ['quest', 'dailies'] },
  ] },
  { title: 'Info & admin', blurb: 'Help, the player panel link and staff tools.', cmds: [
    { usage: '/shopkeeper spawn <name> [market|shop] [mob]', does: 'Staff: place a villager (or any mob) that opens the market when right-clicked. It never moves and is marked on the map.', perm: 'velora.command.market.point' },
    { usage: '/shopkeeper link <name> · remove <name> · list', does: 'Staff: turn the mob you look at into a shopkeeper, free it again, or list them.', perm: 'velora.command.market.point' },
    { usage: '/adminclaim create <name> [description]', does: 'Staff: protect the chunk you stand in as server land with a name and description. Also manage them in the admin panel.', perm: 'velora.admin.claims', aliases: ['/aclaim'] },
    { usage: '/customitem give <player> <id>', does: 'Staff: hand out an item designed in the admin panel.', perm: 'velora.admin.customitem' },
    { usage: '/playtime', does: 'Check your total and session playtime.', perm: 'velora.command.playtime', aliases: ['ontime'] },
    { usage: '/hand', does: 'Share your held item as an inspectable chat link.', perm: 'velora.command.hand' },
    { usage: '/nick <name|off>', does: 'Set or remove your chat nickname.', perm: 'velora.command.nick' },
    { usage: '/velora help', does: 'List the Velora commands you can use.', perm: 'velora.command.velora.help', aliases: ['scopenet', 'sn'] },
    { usage: '/velora panel', does: 'Get the link to the player panel: market, casino, friends, guilds and quests in any browser or phone. Sign in with your launcher account.', perm: 'velora.command.velora.panel', aliases: ['/velora web', '/velora app'] },
    { usage: '/velora status', does: 'Panel connection, features and plugin integrations (admins).', perm: 'velora.command.velora.status' },
    { usage: '/velora reload', does: 'Reload the plugin config (admins).', perm: 'velora.command.velora.reload' },
  ] },
];

export const COMMAND_TIPS = [
  'Press Ctrl+K in the launcher, the player panel or the admin panel to jump anywhere or find a command instantly.',
  'With Velora Core (Client) installed: K opens the hub (Market, Darknet, Casino, Faction, Map, Vault 1), M opens the map and V opens Vault 1. Claims are selected on the map with right-click, then Claim or Unclaim.',
  'The player panel works on your phone: market, casino, friends, factions, quests, leaderboards and the live map. Type /velora panel in game for the link, then use “Add to Home Screen”.',
  'Placeholders: use %velora_level%, %velora_guild%, %velora_balance% and more in scoreboards, tab and chat. Placeholder API on Fabric uses %velora:level%; the older %scopenet:…% names still work.',
  'Walking into claimed land shows the faction (or the server area and its description) above your hotbar. Your bell in the title bar collects faction, auction and quest news.',
  'Right-click a shop point (a marked block) to open the market or shop. A pedestal shop (polished blackstone slab) opens a purchase screen with Velora Core (Client).',
  'Some commands may be switched off or limited by the server. If one says you lack permission, ask an admin.',
  'Everything here also works through your rank: servers using LuckPerms can grant each permission node to any group. Nodes now start with velora.; older scopenet. nodes are still honoured.',
];
