/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=control-plane/wrangler.jsonc --include-runtime=false --strict-vars=false control-plane/worker-configuration.d.ts` (hash: f3ab77ead106b7b6c8dee630a9896524)
interface __BaseEnv_Env {
	OPERATIONS: R2Bucket;
	HARNESS_DB: D1Database;
	IDENTITY_DB: D1Database;
	ENVIRONMENT: string;
	BUILD_SHA: string;
	BOOTSTRAP_ENABLED: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	BOOTSTRAP_OPERATOR_EMAIL: string;
	CONTROL_API_ENABLED: string;
	CI_OIDC_AUDIENCE: string;
	CI_API_HOST: string;
	OPERATOR_API_HOST: string;
	WEBHOOKS_ENABLED: string;
	AGENTS_ENABLED: string;
	PROBE_DEPLOYMENTS_ENABLED: string;
	PROBE_SIGNING_PUBLIC_KEY: string;
	BINDING_CHECK: Workflow<Parameters<import("./src/index").BindingCheckWorkflow['run']>[0]['payload']>;
	PROBE_DEPLOYMENT: Workflow<Parameters<import("./src/index").ProbeDeploymentWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "BUILD_SHA" | "BOOTSTRAP_ENABLED" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "BOOTSTRAP_OPERATOR_EMAIL" | "CONTROL_API_ENABLED" | "CI_OIDC_AUDIENCE" | "CI_API_HOST" | "OPERATOR_API_HOST" | "WEBHOOKS_ENABLED" | "AGENTS_ENABLED" | "PROBE_DEPLOYMENTS_ENABLED" | "PROBE_SIGNING_PUBLIC_KEY">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}