pub mod account;
pub mod achievements;
pub mod activity;
pub mod admin;
pub mod admin_claims;
pub mod auctions;
pub mod bulk;
pub mod casino;
pub mod casino_admin;
pub mod chat;
pub mod collections;
pub mod companion;
pub mod connections;
pub mod content;
pub mod contracts;
pub mod cosmetics;
pub mod dev_api;
pub mod darknet;
pub mod discord;
pub mod discord_commands;
pub mod discord_studio;
pub mod economy;
pub mod economy_admin;
pub mod emails;
pub mod events;
pub mod factions;
pub mod guild_bank;
pub mod guild_flags;
pub mod guild_game;
pub mod guilds;
pub mod icon_library;
pub mod integrations;
pub mod landing;
pub mod core_releases;
pub mod launcher_releases;
pub mod operations;
pub mod launcher_updates;
pub mod ledger;
pub mod leveling;
pub mod luckperms;
pub mod mc_assets;
pub mod map;
pub mod market;
pub mod meta;
pub mod mobile_apps;
pub mod notifications;
pub mod orders;
pub mod progression;
pub mod public;
pub mod quests;
pub mod resource_assets;
pub mod rewards;
pub mod servers;
pub mod social;
pub mod utilities;
pub mod vaults;
pub mod vault_transfers;
pub mod physical_shops;
pub mod outposts;
pub mod worldmap;

use crate::state::AppState;
use axum::extract::DefaultBodyLimit;
use axum::routing::{delete, get, post, put};
use axum::Router;

pub fn api(state: &AppState) -> Router<AppState> {
    let upload_limit = state.cfg.max_upload_mb * 1024 * 1024;

    let launcher = Router::new()
        .route("/resource-pack.zip", get(resource_assets::download))
        .route("/icons/{pack}/{file}", get(icon_library::svg))
        .route("/mc/status", get(mc_assets::status))
        .route("/mc/{kind}/{*file}", get(mc_assets::texture))
        .route("/launcher/manifest", get(public::manifest))
        .route("/launcher/update", get(launcher_updates::latest))
        .route("/core/latest", get(core_releases::latest))
        .route("/core/files/{digest}/{name}", get(core_releases::download))
        .route("/mobile-apps", get(mobile_apps::public_get))
        .route("/mobile-apps/altstore.json", get(mobile_apps::altstore))
        .route("/mobile-apps/{platform}/download", get(mobile_apps::download))
        .route("/launcher/updates/{digest}/setup.exe", get(launcher_updates::download))
        .route("/launcher/updates/{digest}/{name}", get(launcher_updates::download_file))
        .route("/launcher/instances/{id}", get(public::instance_manifest))
        .route("/launcher/events", post(public::event))
        .route("/instances", get(admin::list_instances))
        .route("/auth/login", post(public::login))
        .route("/auth/register", post(public::register))
        .route("/auth/me", get(public::me))
        .route("/auth/connections/config", get(connections::public_config))
        .route("/auth/forgot-password", post(connections::forgot_password))
        .route("/auth/reset-password", post(connections::reset_password))
        .route("/auth/discord/start", get(connections::discord_start))
        .route("/auth/discord/callback", get(connections::discord_callback))
        .route("/auth/discord/poll", get(connections::discord_poll))
        .route("/account/discord", get(discord::public_info))
        .route("/account/connections/discord", get(connections::my_discord).delete(connections::unlink_discord))
        .route("/account/profile", get(account::profile))
        .route("/account/stats", get(servers::account_player_stats))
        .route("/account/username", axum::routing::put(account::set_username))
        .route("/account/skin", post(account::upload_skin).delete(account::delete_skin))
        .route("/account/skin/model", axum::routing::put(account::set_model))
        .route("/account/cape", axum::routing::put(account::set_cape))
        .route("/avatar/{id}", get(account::avatar))
        .route("/servers/public", get(servers::public_servers))
        .route("/servers/{id}/leaderboard", get(servers::public_server_leaderboard))
        .route("/servers/{id}/map", get(worldmap::viewer_info))
        .route("/servers/{id}/map/overlay", get(worldmap::viewer_overlay))
        .route("/servers/{id}/map/actions", post(map::map_action))
        .route("/guilds/invites", get(map::my_invites))
        .route("/guilds/invites/{id}/accept", post(map::accept_invite))
        .route("/guilds/invites/{id}/decline", post(map::decline_invite))
        .route("/guilds/{id}/invites", post(map::send_invite))
        .route("/leaderboard", get(servers::global_leaderboard))
        .route("/landing", get(landing::public_landing))
        .route("/public/map/{id}", get(worldmap::public_info))
        .route("/public/map/{id}/overlay", get(worldmap::public_overlay))
        .route("/email/unsubscribe", get(emails::unsubscribe))
        .route("/discord/interactions", post(discord_commands::interactions))
        .route("/launcher/authlib-injector.json", get(account::authlib_index))
        .route("/launcher/authlib-injector.jar", get(account::authlib_jar))
        // Leveling & Rewards
        .route("/levels/me", get(leveling::get_my_levels))
        .route("/leveling/me", get(leveling::get_my_levels))
        .route("/levels/player/{uuid}", get(leveling::get_player_levels))
        .route("/levels/leaderboard", get(leveling::get_level_leaderboard))
        .route("/levels/rewards", get(leveling::list_rewards))
        // Notification bell
        .route("/notifications", get(notifications::list).delete(notifications::clear))
        .route("/notifications/read", post(notifications::mark_read))
        .route("/notifications/{id}", delete(notifications::remove))
        // Daily & Weekly Quests
        .route("/quests/my", get(quests::get_my_quests))
        .route("/quests/me", get(quests::get_my_quests))
        .route("/quests/{id}/claim", post(quests::claim_quest))
        .route("/reward-bundles", get(rewards::public_summaries))
        .route("/collections/me", get(collections::mine))
        .route("/collections/equip", post(collections::equip))
        .route("/events", get(events::list_public))
        .route("/events/{id}/join", post(events::join))
        .route("/events/{id}", get(events::detail))
        // Achievements
        .route("/achievements/my", get(achievements::get_my_achievements))
        .route("/achievements/me", get(achievements::get_my_achievements))
        .route("/achievements/player/{uuid}", get(achievements::get_player_achievements))
        // Guilds & Land Claims
        .route("/guilds", get(guilds::list_guilds).post(guilds::create_guild))
        .route("/guilds/my", get(guilds::get_my_guild))
        .route("/guilds/memberships", get(guilds::my_memberships))
        .route("/guilds/{id}/primary", post(guilds::set_primary_guild))
        .route("/guilds/claims/grid", get(guilds::get_chunk_grid))
        .route("/guilds/claims/{id}", delete(guilds::unclaim_by_id))
        .route("/guilds/{id}", get(guilds::get_guild_by_id).put(guilds::update_guild).delete(guilds::disband_guild))
        .route("/guilds/{id}/name", put(guilds::rename_guild))
        .route("/guilds/{id}/leader", put(guilds::transfer_guild_leader))
        .route("/guilds/{id}/members", get(guilds::get_guild_members).post(guilds::add_guild_member))
        .route("/guilds/{id}/members/{uuid}/role", put(guilds::assign_guild_role))
        .route("/guilds/{id}/roles", get(guilds::list_guild_roles).post(guilds::create_guild_role))
        .route("/guilds/{id}/roles/{role_id}", delete(guilds::delete_guild_role))
        .route("/guilds/{id}/requests", get(guilds::list_join_requests).post(guilds::request_join))
        .route("/guilds/{id}/requests/{uuid}/respond", post(guilds::respond_join_request))
        .route("/guilds/{id}/members/{uuid}", delete(guilds::remove_guild_member))
        .route("/guilds/{id}/posts", get(guilds::get_guild_posts).post(guilds::create_guild_post))
        .route("/guilds/{id}/wallet", get(guilds::guild_wallet))
        .route("/guilds/{id}/wallet/deposit", post(guilds::guild_wallet_deposit))
        .route("/guilds/{id}/wallet/withdraw", post(guilds::guild_wallet_withdraw))
        .route("/guilds/{id}/claim-flags", get(guild_flags::get).put(guild_flags::put))
        .route("/guilds/{id}/claims", post(guilds::claim_chunk).delete(guilds::unclaim_chunk))
        .route("/guilds/{id}/relations", get(guilds::list_relations).post(guilds::create_relation))
        .route("/guilds/{id}/relations/{relation_id}/respond", post(guilds::decide_relation))
        .route("/guilds/{id}/upgrades", get(factions::get_upgrades).post(factions::buy_upgrade))
        .route("/guilds/{id}/claim", post(guilds::claim_chunk))
        .route("/guilds/{id}/unclaim", post(guilds::unclaim_chunk))
        // Economy
        .route("/board/{sid}/orders", get(orders::orders_board).post(orders::create))
        .route("/board/{sid}/orders/{id}/cancel", post(orders::cancel))
        .route("/board/{sid}/orders/{id}/claim", post(orders::claim))
        .route("/board/{sid}/orders/{id}/release", post(orders::release))
        .route("/board/{sid}/contracts", get(contracts::contracts_board))
        .route("/board/{sid}/contracts/{id}/abandon", post(contracts::abandon))
        .route("/market/{server_id}", get(market::listings))
        .route("/market/{server_id}/mine", get(market::mine))
        .route("/market/{server_id}/buy", post(market::buy))
        .route("/market/{server_id}/bid", post(market::bid))
        .route("/market/{server_id}/cancel", post(market::cancel))
        .route("/casino/{sid}", get(casino::lobby))
        .route("/casino/{sid}/history", get(casino::history))
        .route("/casino/{sid}/players", get(casino::players))
        .route("/casino/{sid}/slots", post(casino::slots))
        .route("/casino/{sid}/wheel", post(casino::wheel))
        .route("/casino/{sid}/plinko", post(casino::plinko))
        .route("/casino/{sid}/dice", post(casino::dice))
        .route("/casino/{sid}/coinflip", post(casino::coinflip))
        .route("/casino/{sid}/roulette", post(casino::roulette))
        .route("/casino/{sid}/burst/start", post(casino::burst_start))
        .route("/casino/{sid}/burst/advance", post(casino::burst_advance))
        .route("/casino/{sid}/burst/cashout", post(casino::burst_cashout))
        .route("/casino/{sid}/double", post(casino::double))
        .route("/casino/{sid}/crash/start", post(casino::crash_start))
        .route("/casino/{sid}/crash/status", get(casino::crash_status))
        .route("/casino/{sid}/crash/cashout", post(casino::crash_cashout))
        .route("/casino/{sid}/blackjack/start", post(casino::blackjack_start))
        .route("/casino/{sid}/blackjack/hit", post(casino::blackjack_hit))
        .route("/casino/{sid}/blackjack/stand", post(casino::blackjack_stand))
        .route("/casino/{sid}/blackjack/double", post(casino::blackjack_double))
        .route("/casino/{sid}/daily", post(casino::daily))
        .route("/casino/{sid}/mines/start", post(casino::mines_start))
        .route("/casino/{sid}/mines/reveal", post(casino::mines_reveal))
        .route("/casino/{sid}/mines/cashout", post(casino::mines_cashout))
        .route("/casino/{sid}/bounties", get(casino::bounties).post(casino::place_bounty))
        .route("/casino/{sid}/bounties/{id}/cancel", post(casino::cancel_bounty))
        .route("/casino/{sid}/markets", get(casino::markets).post(casino::create_market))
        .route("/casino/{sid}/markets/{id}/bet", post(casino::place_bet))
        .route("/casino/{sid}/markets/{id}/cancel", post(casino::cancel_market))
        .route("/economy/me", get(economy::get_my_balances))
        .route("/board/{sid}/darknet", get(darknet::player_catalog))
        .route("/vaults/{sid}", get(vaults::player_list))
        .route("/vaults/{sid}/move", post(vaults::player_move))
        .route("/vaults/{sid}/buy", post(vaults::player_buy))
        .route("/board/{sid}/darknet/buy", post(darknet::player_buy))
        .route("/economy/balances", get(economy::get_my_balances))
        .route("/economy/balance/{server_id}", get(economy::get_my_balance_on))
        .route("/economy/transactions", get(economy::get_my_transactions))
        .route("/servers/{id}/economy/baltop", get(economy::get_server_baltop))
        .route("/servers/{id}/economy/market", get(economy::get_server_market))
        // Social: Friends, DMs, Invites, Profiles, Posts, Members Search
        .route("/friends", get(social::list_friends))
        .route("/friends/request", post(social::send_friend_request))
        .route("/friends/respond", post(social::respond_friend_request))
        .route("/friends/{uuid}/accept", post(social::accept_friend_request))
        .route("/friends/{uuid}", delete(social::remove_friend))
        .route("/messages/{uuid}", get(social::get_direct_messages).post(social::send_direct_message))
        .route("/invites", get(social::list_my_game_invites).post(social::send_game_invite))
        .route("/invites/{id}/respond", post(social::respond_game_invite))
        .route("/profiles/me", put(social::update_my_profile))
        .route("/profiles/{uuid}", get(social::get_player_profile))
        .route("/profiles/me/posts", post(social::create_user_post))
        .route("/profiles/me/posts/{id}", delete(social::delete_user_post))
        .route("/posts/{id}/like", post(social::like_user_post))
        .route("/social/friends", get(social::list_friends))
        .route("/social/friends/request", post(social::send_friend_request))
        .route("/social/friends/respond", post(social::respond_friend_request))
        .route("/social/messages/{uuid}", get(social::get_direct_messages).post(social::send_direct_message))
        .route("/social/profile/me", put(social::update_my_profile))
        .route("/social/profile/{uuid}", get(social::get_player_profile))
        .route("/social/posts", post(social::create_user_post))
        .route("/social/posts/{id}/like", post(social::like_user_post))
        .route("/social/members", get(social::search_members))
        .route("/members/search", get(social::search_members))
        .layer(DefaultBodyLimit::max(4 * 1024 * 1024));

    let admin = Router::new()
        .route("/instances/{id}/experience", axum::routing::put(crate::experience::configure))
        .route("/instances/{id}/velora-core/activate", post(crate::velora_core::activate))
        .route("/economy/darknet", get(darknet::admin_get).put(darknet::admin_put))
        .route("/icons/packs", get(icon_library::packs))
        .route("/mc-textures", get(mc_assets::admin_get).delete(mc_assets::admin_clear))
        .route("/mc-textures/fetch", post(mc_assets::admin_fetch))
        .route("/mc-textures/upload", post(mc_assets::admin_upload).layer(DefaultBodyLimit::max(mc_assets::MAX_JAR as usize + 1024 * 1024)))
        .route("/icons/search", get(icon_library::search))
        .route("/resource-assets", get(resource_assets::list).post(resource_assets::upload).layer(DefaultBodyLimit::max(4 * 1024 * 1024)))
        .route("/content", get(content::list))
        .route("/content/analyze", post(content::analyze).layer(DefaultBodyLimit::max(48 * 1024 * 1024)))
        .route("/content/import", post(content::import).layer(DefaultBodyLimit::max(48 * 1024 * 1024)))
        .route("/content/view", get(content::view))
        .route("/content/{id}", get(content::get_one).put(content::save).delete(content::delete))
        .route("/resource-assets-check", get(resource_assets::check))
        .route("/resource-assets-browse", get(resource_assets::browse))
        .route("/resource-assets-preview", get(resource_assets::asset_preview))
        .route("/resource-assets-import", post(resource_assets::import_pack).layer(DefaultBodyLimit::max(48 * 1024 * 1024)))
        .route("/resource-assets/{*path}", delete(resource_assets::remove))
        .route("/resource-pack", put(resource_assets::configure))
        .route("/connections", get(connections::admin_get).put(connections::admin_put))
        .route("/connections/test-email", post(connections::admin_test_email))
        .route("/activity", get(activity::list))
        .route("/stats", get(admin::stats))
        .route("/operations/summary", get(operations::summary))
        .route("/chat", get(chat::get).put(chat::put))
        .route("/utilities", get(utilities::get).put(utilities::put))
        .route("/custom-items", get(utilities::list_items))
        .route("/custom-items/{id}", put(utilities::save_item).delete(utilities::delete_item))
        .route("/servers/{id}/admin-claims", get(admin_claims::list).post(admin_claims::create))
        .route("/admin-claims/{id}", axum::routing::patch(admin_claims::update).delete(admin_claims::delete))
        .route("/admin-claims/{id}/area", post(admin_claims::area))
        .route("/casino", get(casino_admin::get).put(casino_admin::save))
        .route("/casino/preview", post(casino_admin::preview_route))
        .route("/casino/stats", get(casino_admin::stats))
        .route("/casino/bounties", get(casino_admin::list_bounties))
        .route("/casino/bounties/{id}/cancel", post(casino_admin::cancel_bounty))
        .route("/casino/markets", get(casino_admin::list_markets))
        .route("/casino/markets/{id}/void", post(casino_admin::void_market))
        .route("/economy/overview", get(economy_admin::overview))
        .route("/economy/players", get(economy_admin::players))
        .route("/economy/players/adjust", post(economy_admin::adjust_player))
        .route("/economy/accounts/missing", get(economy_admin::missing))
        .route("/economy/accounts/repair", post(economy_admin::repair))
        .route("/economy/accounts/assign", post(economy_admin::assign))
        .route("/economy/guilds", get(economy_admin::guilds))
        .route("/economy/guilds/adjust", post(economy_admin::adjust_guild))
        .route("/economy/orders", get(orders::admin_get).put(orders::admin_save))
        .route("/economy/orders/{id}/cancel", post(orders::admin_cancel))
        .route("/economy/contracts", get(contracts::admin_get).put(contracts::admin_save))
        .route("/economy/market", get(economy_admin::market))
        .route("/economy/market/{id}/remove", post(economy_admin::remove_listing))
        .route("/economy/market/{id}/extend", post(economy_admin::extend_auction))
        .route("/economy/market/{id}/price", post(economy_admin::set_price))
        .route("/economy/transactions", get(economy_admin::transactions))
        .route("/tasks", get(crate::scheduler::list))
        .route("/tasks/{id}", put(crate::scheduler::update))
        .route("/tasks/{id}/run", post(crate::scheduler::run))
        .route("/users", get(admin::list_users).post(admin::create_user))
        .route("/users/{id}", axum::routing::patch(admin::update_user).delete(admin::delete_user))
        .route("/instance-groups", get(admin::list_groups))
        .route("/groups", get(admin::list_groups).post(admin::create_group))
        .route("/groups/{id}", delete(admin::delete_group))
        .route("/branding", get(admin::get_branding).put(admin::put_branding))
        .route("/settings", get(admin::get_settings).put(admin::put_settings))
        .route("/landing", get(landing::admin_get_landing).put(landing::admin_put_landing))
        .route("/landing/upload-launcher", post(landing::upload_launcher))
        .route("/landing/launcher/{platform}", delete(landing::remove_launcher))
        .route("/launcher/update", get(launcher_updates::admin_get).post(launcher_updates::upload).delete(launcher_updates::admin_remove))
        .route("/launcher/releases", get(launcher_releases::list))
        .route("/launcher/releases/{tag}/approve", post(launcher_releases::approve))
        .route("/core/releases", get(core_releases::list))
        .route("/core/releases/{tag}/approve", post(core_releases::approve))
        .route("/mobile-apps", get(mobile_apps::admin_get).post(mobile_apps::upload))
        .route("/mobile-apps/{platform}", delete(mobile_apps::remove))
        .route("/instances", get(admin::list_instances).post(admin::create_instance))
        .route("/instances/{id}", get(admin::get_instance).put(admin::update_instance).delete(admin::delete_instance))
        .route("/instances/{id}/reset", post(admin::reset_source))
        .route("/instances/{id}/clean-update", post(admin::clean_update))
        .route("/instances/{id}/import/modrinth", post(admin::import_modrinth))
        .route("/instances/{id}/import/curseforge", post(admin::import_curseforge))
        .route("/instances/{id}/import/upload", post(admin::import_upload))
        .route("/instances/{id}/files", post(admin::upload_files).delete(admin::delete_file))
        .route("/uploads", post(admin::upload_media))
        .route("/users/{id}/skin", post(admin::admin_set_skin).delete(admin::admin_delete_skin))
        .route("/users/{id}/skin/model", axum::routing::put(admin::admin_set_model))
        .route("/users/{id}/cape", axum::routing::put(admin::admin_set_cape))
        .route("/capes", get(admin::list_capes).post(admin::create_cape))
        .route("/capes/{id}", axum::routing::put(admin::update_cape).delete(admin::delete_cape))
        .route("/auth-server", get(admin::auth_server_info))
        .route("/servers", get(servers::list).post(servers::create))
        .route("/servers/{id}", get(servers::detail).put(servers::update).delete(servers::remove))
        .route("/servers/{id}/token", post(servers::regenerate_token))
        .route("/servers/{id}/map", get(worldmap::admin_status).delete(worldmap::admin_reset))
        .route("/users/{id}/activity", get(servers::user_activity))
        .route("/meta/minecraft", get(meta::minecraft))
        .route("/meta/loaders/{loader}", get(meta::loaders))
        .route("/modrinth/search", get(meta::modrinth_search))
        .route("/modrinth/project/{id}/versions", get(meta::modrinth_versions))
        .route("/curseforge/search", get(meta::curseforge_search))
        .route("/curseforge/mod/{id}/files", get(meta::curseforge_files))
        // Admin Quests & Achievements & Rewards & Guilds
        .route("/rewards", get(leveling::list_rewards).post(leveling::admin_create_reward))
        .route("/rewards/{id}", put(leveling::admin_update_reward).delete(leveling::admin_delete_reward))
        .route("/levels/rewards", get(leveling::list_rewards).post(leveling::admin_create_reward))
        .route("/levels/rewards/{id}", put(leveling::admin_update_reward).delete(leveling::admin_delete_reward))
        .route("/levels/sync-titles", post(leveling::admin_sync_titles))
        .route("/email", get(emails::get_all))
        .route("/email/templates", put(emails::put_templates))
        .route("/email/preview", post(emails::preview))
        .route("/email/audience", post(emails::audience))
        .route("/email/send", post(emails::send))
        .route("/discord/studio", get(discord_studio::get_all))
        .route("/discord/studio/templates", put(discord_studio::put_templates))
        .route("/discord/studio/live", put(discord_studio::put_live))
        .route("/discord/studio/preview", post(discord_studio::preview))
        .route("/discord/studio/send/{kind}", post(discord_studio::send_now))
        .route("/discord/studio/repost/{kind}", post(discord_studio::repost))
        .route("/bulk/{kind}", get(bulk::list).post(bulk::save))
        .route("/quests", get(quests::admin_list_quests).post(quests::admin_create_quest))
        .route("/quests/{id}", put(quests::admin_update_quest).delete(quests::admin_delete_quest))
        .route("/quest-chains", get(quests::list_chains).post(quests::create_chain))
        .route("/quest-chains/{id}", put(quests::update_chain).delete(quests::delete_chain))
        .route("/achievements", get(achievements::admin_list_achievements).post(achievements::admin_create_achievement))
        .route("/achievements/{id}", put(achievements::admin_update_achievement).delete(achievements::admin_delete_achievement))
        .route("/progression", get(progression::get_settings).put(progression::put_settings))
        .route("/progression/auto-money/apply", post(progression::apply_auto_money))
        .route("/progression/players", get(progression::list_players))
        .route("/progression/players/{uuid}", get(progression::get_player))
        .route("/progression/players/{uuid}/adjust", post(progression::adjust_player))
        .route("/events", get(events::admin_list).post(events::admin_create))
        .route("/events/{id}", put(events::admin_update).delete(events::admin_delete))
        .route("/players/{uuid}/collections", get(collections::admin_player))
        .route("/collections/grant", post(collections::grant))
        .route("/collections/{uuid}/{key}", delete(collections::revoke))
        .route("/cosmetics/templates", get(cosmetics::list).post(cosmetics::create))
        .route("/cosmetics/templates/{id}", get(cosmetics::get).put(cosmetics::update).delete(cosmetics::delete))
        .route("/reward-bundles/{kind}/{id}", get(rewards::admin_get).put(rewards::admin_put))
        .route("/reward-deliveries", get(rewards::admin_deliveries))
        .route("/reward-deliveries/{id}/retry", post(rewards::admin_retry_delivery))
        .route("/reward-deliveries/{id}", delete(rewards::admin_delete_delivery))
        .route("/reward-deliveries/clear-delivered", post(rewards::admin_clear_delivered))
        .route("/companion/layouts", get(companion::list_layouts).post(companion::create_layout))
        .route("/companion/layouts/{id}", get(companion::get_layout).put(companion::update_layout).delete(companion::delete_layout))
        .route("/companion/layouts/{id}/set-default", post(companion::set_default_layout))
        .route("/email-templates", get(emails::list_templates).post(emails::create_template))
        .route("/email-templates/{id}", get(emails::get_template).put(emails::update_template).delete(emails::delete_template))
        .route("/email-templates/test", post(emails::send_test_email))
        .route("/guild-flag-policy", get(guild_flags::admin_get).put(guild_flags::admin_put))
        .route("/luckperms", get(luckperms::overview))
        .route("/luckperms/groups", post(luckperms::create_group))
        .route("/luckperms/groups/{name}", put(luckperms::update_group).delete(luckperms::delete_group))
        .route("/luckperms/groups/{name}/permissions", post(luckperms::set_permission).delete(luckperms::unset_permission))
        .route("/luckperms/groups/{name}/parents", post(luckperms::add_parent))
        .route("/luckperms/groups/{name}/parents/{parent}", delete(luckperms::remove_parent))
        .route("/luckperms/level-links", put(luckperms::put_level_links))
        .route("/luckperms/players", get(luckperms::players))
        .route("/luckperms/players/bulk-move", post(luckperms::bulk_move))
        .route("/luckperms/players/{uuid}/groups", post(luckperms::move_player))
        .route("/luckperms/commands", delete(luckperms::clear_commands))
        .route("/luckperms/commands/{id}/retry", post(luckperms::retry_command))
        .route("/integrations/settings", get(integrations::get_settings).put(integrations::put_settings))
        .route("/groups/{id}/luckperms", put(integrations::set_group_mapping))
        .route("/groups/{id}/discord-role", put(discord::set_role_mapping))
        .route("/discord", get(discord::get_settings).put(discord::put_settings))
        .route("/discord/roles", get(discord::roles))
        .route("/discord/sync", post(discord::sync_now))
        .route("/discord/commands/register", post(discord_commands::register))
        .route("/discord/test", post(discord::test_announce))
        .route("/discord/channels", get(discord::channels))
        .route("/servers/{id}/integrations", get(integrations::admin_server))
        .route("/guilds", get(guilds::admin_list_guilds))
        .route("/guilds/{id}", delete(guilds::admin_delete_guild).put(guilds::admin_rename_guild))
        .layer(DefaultBodyLimit::max(upload_limit));

    // Called by the Velora Paper plugin and Fabric/Forge mods.
    let game = Router::new()
        .route("/resource-pack", post(resource_assets::game_config))
        .route("/kits/create", post(utilities::game_create_kit))
        .route("/companion", post(companion::request))
        .route("/hello", post(servers::hello))
        .route("/login", post(servers::login))
        .route("/sync", post(servers::sync))
        .route("/guilds/check-chunk", post(guilds::server_check_chunk))
        .route("/guilds/claim-snapshot", post(guilds::server_claim_snapshot))
        .route("/guilds/claim-index", post(guilds::server_claim_index))
        .route("/admin-claims", post(admin_claims::game))
        .route("/guilds/claim", post(guilds::server_claim_chunk))
        .route("/guilds/unclaim", post(guilds::server_unclaim_chunk))
        .route("/guilds/player", post(guilds::server_get_player_guild))
        .route("/guilds/create", post(guilds::server_create_guild))
        .route("/guilds/leave", post(guilds::server_guild_leave))
        .route("/guilds/rename", post(guilds::server_guild_rename))
        .route("/guilds/disband", post(guilds::server_guild_disband))
        .route("/guilds/manage", post(guild_game::server_guild_manage))
        .route("/quests/player", post(quests::server_player_quests))
        .route("/cosmetics/list", post(collections::server_list))
        .route("/cosmetics/equip", post(collections::server_equip))
        .route("/integrations/report", post(integrations::server_report))
        .route("/actions/poll", post(map::poll_actions))
        .route("/rewards/poll", post(rewards::game_poll))
        .route("/rewards/ack", post(rewards::game_ack))
        .route("/guilds/invite/send", post(map::server_invite_send))
        .route("/guilds/invite/list", post(map::server_invites))
        .route("/guilds/invite/respond", post(map::server_invite_respond))
        .route("/player/info", post(dev_api::player_info))
        .route("/player/xp", post(dev_api::add_xp))
        .route("/player/quest-objective", post(dev_api::quest_objective))
        .route("/player/friends", post(dev_api::friends))
        .route("/guild/info", post(dev_api::guild))
        .route("/guilds/bank", post(guild_bank::server_bank_info))
        .route("/guilds/upgrades", post(factions::server_upgrades))
        .route("/guilds/bank/transfer", post(guild_bank::server_bank_transfer))
        .route("/guilds/bank/credit", post(guild_bank::server_bank_credit))
        .route("/guilds/bank/pay", post(guild_bank::server_bank_pay))
        .route("/economy/balance", post(economy::server_get_balance))
        .route("/economy/pay", post(economy::server_transfer))
        .route("/economy/transfer", post(economy::server_transfer))
        .route("/economy/darknet", post(darknet::game_catalog))
        .route("/economy/darknet/buy", post(darknet::game_buy))
        .route("/economy/physical-shops", post(physical_shops::index))
        .route("/economy/physical-shops/create", post(physical_shops::create).layer(DefaultBodyLimit::max(2 * 1024 * 1024)))
        .route("/economy/physical-shops/buy", post(physical_shops::buy))
        .route("/economy/physical-shops/promote", post(physical_shops::promote))
        .route("/economy/physical-shops/update", post(physical_shops::update))
        .route("/economy/adjust", post(economy::server_adjust_balance))
        .route("/economy/market", post(economy::server_market_read))
        .route("/economy/sync-balance", post(economy::server_sync_balance))
        .route("/economy/baltop", post(economy::server_baltop))
        .route("/economy/market/list", post(economy::server_market_list))
        .route("/economy/market/buy", post(economy::server_market_buy))
        .route("/economy/market/bid", post(auctions::server_bid))
        .route("/economy/market/cancel", post(auctions::server_cancel))
        .route("/economy/orders", post(orders::server_list))
        .route("/economy/orders/create", post(orders::server_create))
        .route("/economy/orders/cancel", post(orders::server_cancel))
        .route("/economy/orders/claim", post(orders::server_claim))
        .route("/economy/orders/release", post(orders::server_release))
        .route("/economy/orders/fill", post(orders::server_fill))
        .route("/economy/contracts", post(contracts::server_list))
        .route("/economy/contracts/submit", post(contracts::server_submit))
        .route("/economy/contracts/abandon", post(contracts::server_abandon))
        .route("/economy/market/mailbox", post(auctions::server_mailbox_count))
        .route("/economy/market/mailbox/claim", post(auctions::server_mailbox_claim))
        .route("/economy/market/vault", post(auctions::server_vault_pull))
        .route("/economy/market/vault/ack", post(auctions::server_vault_ack))
        .route("/vault/open", post(vaults::game_open))
        .route("/vault/transfers/prepare", post(vault_transfers::prepare).layer(DefaultBodyLimit::max(8 * 1024 * 1024)))
        .route("/vault/transfers/finish", post(vault_transfers::finish))
        .route("/vault/transfers/pending", post(vault_transfers::pending))
        .route("/guilds/outposts/place", post(outposts::place))
        .route("/vault/save", post(vaults::game_save).layer(DefaultBodyLimit::max(8 * 1024 * 1024)))
        .route("/vault/renew", post(vaults::game_renew))
        .route("/vault/import", post(vaults::game_import).layer(DefaultBodyLimit::max(64 * 1024 * 1024)))
        .route("/vault/buy", post(vaults::game_buy))
        .route("/vault/entitlements", post(vaults::game_entitlements))
        .layer(DefaultBodyLimit::max(2 * 1024 * 1024));

    // Map ingest: tile batches are larger than the other game calls.
    let map_game = Router::new()
        .route("/map/config", get(worldmap::game_config))
        .route("/map/tiles", post(worldmap::game_tiles))
        .route("/map/players", post(worldmap::game_players))
        .route("/map/overlay", post(worldmap::game_overlay))
        .route("/map/diagnostics", post(worldmap::game_diagnostics))
        .layer(DefaultBodyLimit::max(10 * 1024 * 1024));

    Router::new()
        .route("/api/server/v1/experience/modules/{module}", put(crate::experience::publish_module))
        .route("/api/experience-map/{instance}/{id}/{dim}/{z}/{x}/{file}", get(worldmap::experience_tile))
        .route("/api/map/{id}/{dim}/{z}/{x}/{file}", get(worldmap::tile))
        .nest("/api/v1", launcher)
        .nest("/api/server/v1", game.merge(map_game))
        .nest("/api/admin", admin)
        .merge(crate::yggdrasil::routes(state).layer(DefaultBodyLimit::max(4 * 1024 * 1024)))
        .layer(axum::middleware::from_fn_with_state(state.clone(), activity::audit))
}
