modLoader="javafml"
loaderVersion="[${forge},)"
license="All Rights Reserved"
[[mods]]
modId="scopenet"
version="${version}"
displayName="SCOPENET"
displayTest="IGNORE_ALL_VERSION"
description="Private authentication, access control and activity reporting for SCOPENET servers."
[[dependencies.scopenet]]
modId="forge"
mandatory=true
versionRange="[${forge},)"
ordering="NONE"
side="SERVER"
[[dependencies.scopenet]]
modId="minecraft"
mandatory=true
versionRange="[${mc}]"
ordering="NONE"
side="SERVER"
